name: Hide old plans
description: Hide old plan comments
inputs:
  org:
    description: GitHub organization
    required: true
  repo:
    description: GitHub repository
    required: true
  token:
    description: GitHub token
    required: true
  pr_number:
    description: Pull request number
    required: true
  target:
    description: Target
    required: true
runs:
  using: "composite"
  steps:
    - run: github-comment hide -org ${{ inputs.org }} -repo ${{ inputs.repo }} -pr ${{ inputs.pr_number }} -token ${{ inputs.token }} -condition 'Comment.HasMeta && (Comment.Meta.SHA1 != Commit.SHA1 && Comment.Target == "${{ inputs.target }}")'
      shell: bash
