name: Setup tfcmt
description: Setup tfcmt and github-comment
runs:
  using: "composite"
  steps:
    - run: curl -LO https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.2.0/tfcmt_linux_amd64.tar.gz
      shell: bash

    - run: echo 'ad26205c0ac2369dff94189e243eac95539c4946946060e4a7ad8306895b2606  tfcmt_linux_amd64.tar.gz' | sha256sum --check
      shell: bash

    - run: sudo tar -C /usr/bin/ -zxf tfcmt_linux_amd64.tar.gz
      shell: bash

    - run: curl -LO https://github.com/suzuki-shunsuke/github-comment/releases/download/v3.1.0/github-comment_3.1.0_linux_amd64.tar.gz
      shell: bash

    - run: echo '8d065e8cd47b8913b7fb481fbf746553929197e3eea649a5fd1e7c6b5251d3ee  github-comment_3.1.0_linux_amd64.tar.gz' | sha256sum --check
      shell: bash

    - run: sudo tar -C /usr/bin/ -zxf github-comment_3.1.0_linux_amd64.tar.gz
      shell: bash
